# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Setup Buf CLI
      uses: bufbuild/buf-setup-action@v1 # Installs the Buf CLI
      with:
        version: 'latest' # Or a specific version like '1.27.0'

    - name: Generate Go code with Buf
      run: buf generate

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
